### ISSUE TITLE
Post-processing error in some Teukolsky runs

### ISSUE THREAD

**Issue by jredondoyuste** [GCArullo/bayRing#10]
When running with the following config file (see below), the following line in `bayRing.py` produces an error:

```
os.system('mv {dir}/Algorithm/nschain*.pdf {dir}/Plots/Chains/.'.format(dir = parameters['I/O']['outdir']))
```

So far I created a branch and commented it out, and everything runs correctly. I believe raynest does not produce the nschain.pdf files, so probably this line should be turned into a `try: ... except: ...` statement. 

This is my config file:

```
[I/O]

outdir=/does/not/matter
screen-output = 0

[NR-data]

dir=/some/directory/
catalog    = Teukolsky
ID=a_0.2_A_0.0141_w_1.0_ingoing
error      = resolution
res-level=3
pert-order=lin
l-NR=2
m=2

[Injection-data]

[Model]

template=Kerr
QNM-modes=220
QQNM-modes=None
N-DS-modes=1

[Inference]

nlive=64
maxmcmc=128
t-start=0.0
t-end=125.0
dt-scd=18.3402
sampler = raynest
nnest=4
nensemble=8

[Priors]

```

**Comment by GCArullo** [comment]
Fixed [here](https://github.com/GCArullo/bayRing/commit/3124bdac7a69cd75f54c1f3e75c19a3ceb221641).
